export const routePath = {
  home: "/",
  profile: "/profile",
  experience: "/experience",
  cardCategoy: "/card-category",
  card: "/card",
  socialLinks: "/social-link",
  profileCreate: "/profile-create",
  updateProfile: "/update-profile/:id",
  login: "/login",
  experienceCreate: "/experience-create",
  experienceUpdate: "/experience-update/:id",
  cardCategoryCreate: "/card-category-create",
  cardCategoryUpdate: "/card-category-update/:id",
  cardCreate: "/card-create",
  cardUpdate: "/card-update/:id",
  socialLinkCreate: "/social-link-create",
  socialLinkUpdate: "/social-link-update/:id",
} as const;
